
package Admistrator;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
   
public class NewJFrame1 extends javax.swing.JFrame {
        DefaultTableModel model;
        DateFormat dataformat = new SimpleDateFormat("dd/MM/YY");
        Date data = new Date();
        Calendar cal = Calendar.getInstance();
        DefaultTableModel model2;
        Connection con;
    public NewJFrame1() {
        initComponents();
        add_per.setVisible(false);
        add.setVisible(false);
        showdata();
        showDataCompany();
        date_field2.setText(" " + dataformat.format(data));
        date_field.setText(" " + dataformat.format(data));
        this.setLocationRelativeTo(null);
       //model.addRow(Search_for_a_category.tab_finded.getValueAt(Search_for_a_category.tab_finded.getSelectedRow(), 0).toString());
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmcy","root", "eslam23467859");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Connection Failed");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tab = new javax.swing.JTabbedPane();
        perchasing = new javax.swing.JPanel();
        date_field2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        add_per = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameofdrugs = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        idofDrugs = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        quantityofDrugs = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dateofcomp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        perchasingofdrugs = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        st_date = new javax.swing.JTextField();
        end_date = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        discountofdrugs = new javax.swing.JTextField();
        Reset = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        type_com = new javax.swing.JComboBox<>();
        addToDatabase = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab_toDataBase = new javax.swing.JTable();
        btn_savetodatabase = new javax.swing.JButton();
        update_per = new javax.swing.JButton();
        del_last5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        Selling = new javax.swing.JPanel();
        date_field = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_Sales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        text_total = new javax.swing.JTextField();
        total = new javax.swing.JButton();
        del_last1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nameofcomp = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        idofcomp = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        prodectofcomp = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        stofcomp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        expofcomp = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        purchasingofcomp = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        sellingofcomp = new javax.swing.JTextField();
        Reset_comp = new javax.swing.JButton();
        addTocomp = new javax.swing.JButton();
        updatecomp = new javax.swing.JButton();
        del_comp = new javax.swing.JButton();
        addTocomp1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_comp = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy");
        setName("frame"); // NOI18N

        jPanel1.setLayout(null);

        Tab.setBackground(new java.awt.Color(151, 200, 240));
        Tab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tab.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Tab.setMinimumSize(new java.awt.Dimension(1570, 720));

        perchasing.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        perchasing.setLayout(null);

        date_field2.setEditable(false);
        date_field2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_field2ActionPerformed(evt);
            }
        });
        perchasing.add(date_field2);
        date_field2.setBounds(1390, 80, 106, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Date");
        jLabel6.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel6.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        perchasing.add(jLabel6);
        jLabel6.setBounds(1310, 80, 64, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Perchasing invoice");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        perchasing.add(jLabel3);
        jLabel3.setBounds(640, 10, 240, 34);

        jPanel6.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.setLayout(null);

        jPanel7.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel7.setLayout(null);

        add_per.setBackground(new java.awt.Color(153, 153, 153));
        add_per.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Add Drugs");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ID:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Quantity:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Selling Price:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Purchasing Price:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Expiration Date:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("From");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("To");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("discount:");

        Reset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Type :");

        type_com.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Taps", "Caps", "vail", "sachets", "surp", "supp" }));
        type_com.setToolTipText("");

        javax.swing.GroupLayout add_perLayout = new javax.swing.GroupLayout(add_per);
        add_per.setLayout(add_perLayout);
        add_perLayout.setHorizontalGroup(
            add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, add_perLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
            .addGroup(add_perLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(add_perLayout.createSequentialGroup()
                        .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discountofdrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perchasingofdrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quantityofDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idofDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameofdrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(add_perLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(105, 105, 105)
                            .addComponent(type_com, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, add_perLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(st_date, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel13)
                            .addGap(13, 13, 13)
                            .addComponent(end_date, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        add_perLayout.setVerticalGroup(
            add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(add_perLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameofdrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idofDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityofDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perchasingofdrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(discountofdrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(st_date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(end_date, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(add_perLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(add_perLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(type_com, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel7.add(add_per);
        add_per.setBounds(30, 140, 400, 590);

        addToDatabase.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addToDatabase.setText("Add");
        addToDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToDatabaseActionPerformed(evt);
            }
        });
        jPanel7.add(addToDatabase);
        addToDatabase.setBounds(580, 590, 180, 50);

        tab_toDataBase.setBackground(new java.awt.Color(153, 153, 153));
        tab_toDataBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "ID", "Quantity", "Selling Price", "Purchasing Price", "Expiration data", "Total cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_toDataBase.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tab_toDataBase.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        tab_toDataBase.setShowHorizontalLines(true);
        tab_toDataBase.setShowVerticalLines(true);
        tab_toDataBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_toDataBaseMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tab_toDataBase);

        jPanel7.add(jScrollPane5);
        jScrollPane5.setBounds(570, 170, 970, 376);

        btn_savetodatabase.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_savetodatabase.setText("Save");
        btn_savetodatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_savetodatabaseActionPerformed(evt);
            }
        });
        jPanel7.add(btn_savetodatabase);
        btn_savetodatabase.setBounds(840, 590, 170, 50);

        update_per.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        update_per.setText("Update");
        update_per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_perActionPerformed(evt);
            }
        });
        jPanel7.add(update_per);
        update_per.setBounds(1310, 590, 160, 50);

        del_last5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        del_last5.setText("Delete");
        del_last5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_last5ActionPerformed(evt);
            }
        });
        jPanel7.add(del_last5);
        del_last5.setBounds(1070, 590, 190, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\صور\\shopping-cart-with-pill-foils-copy-space.jpg")); // NOI18N
        jPanel7.add(jLabel16);
        jLabel16.setBounds(-10, 0, 1570, 810);

        jPanel6.add(jPanel7);
        jPanel7.setBounds(0, -30, 1570, 810);

        perchasing.add(jPanel6);
        jPanel6.setBounds(0, 0, 1540, 750);

        Tab.addTab("Perchasing invoices", perchasing);

        Selling.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        Selling.setMinimumSize(new java.awt.Dimension(1570, 720));
        Selling.setLayout(null);

        date_field.setEditable(false);
        date_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date_fieldActionPerformed(evt);
            }
        });
        Selling.add(date_field);
        date_field.setBounds(120, 80, 106, 30);

        tab_Sales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tab_Sales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ID", "Quantity", "Selling Price", "Purchasing Price", "start date", "end date", "Value of discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_Sales.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        tab_Sales.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        tab_Sales.setShowHorizontalLines(true);
        tab_Sales.setShowVerticalLines(true);
        jScrollPane3.setViewportView(tab_Sales);

        Selling.add(jScrollPane3);
        jScrollPane3.setBounds(10, 140, 957, 376);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sales invoice");
        Selling.add(jLabel1);
        jLabel1.setBounds(371, 11, 176, 34);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date");
        jLabel4.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jLabel4.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        Selling.add(jLabel4);
        jLabel4.setBounds(50, 80, 64, 23);

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        Selling.add(btn_search);
        btn_search.setBounds(50, 570, 200, 60);
        Selling.add(text_total);
        text_total.setBounds(1180, 580, 170, 40);

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setText("Total Price");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        Selling.add(total);
        total.setBounds(960, 580, 180, 40);

        del_last1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        del_last1.setText("Delete selected row");
        del_last1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_last1ActionPerformed(evt);
            }
        });
        Selling.add(del_last1);
        del_last1.setBounds(470, 570, 290, 60);

        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel3.setLayout(null);

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\صور\\shopping-cart-with-pill-foils-copy-space.jpg")); // NOI18N
        jPanel3.add(jLabel15);
        jLabel15.setBounds(0, -10, 1568, 760);

        Selling.add(jPanel3);
        jPanel3.setBounds(0, 0, 1570, 720);

        Tab.addTab("Sales invoices", Selling);

        jPanel4.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel18.setText("Search for company");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(670, 20, 260, 40);

        add.setBackground(new java.awt.Color(153, 153, 153));
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Add Company");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Name:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("ID:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Prodect:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("PH_Date:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Expiriation Date:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Purchasing Price:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Selling Price:");

        Reset_comp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Reset_comp.setText("Reset");
        Reset_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reset_compActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sellingofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchasingofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(addLayout.createSequentialGroup()
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addLayout.createSequentialGroup()
                                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addLayout.createSequentialGroup()
                                        .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLayout.createSequentialGroup()
                                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addGroup(addLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(stofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(prodectofcomp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idofcomp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(addLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(expofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Reset_comp, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodectofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchasingofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sellingofcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reset_comp, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jPanel4.add(add);
        add.setBounds(10, 90, 437, 546);

        addTocomp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addTocomp.setText("Save");
        addTocomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTocompActionPerformed(evt);
            }
        });
        jPanel4.add(addTocomp);
        addTocomp.setBounds(770, 540, 144, 39);

        updatecomp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        updatecomp.setText("Update");
        updatecomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatecompActionPerformed(evt);
            }
        });
        jPanel4.add(updatecomp);
        updatecomp.setBounds(990, 540, 144, 39);

        del_comp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        del_comp.setText("Delete");
        del_comp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_compActionPerformed(evt);
            }
        });
        jPanel4.add(del_comp);
        del_comp.setBounds(1230, 540, 150, 40);

        addTocomp1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        addTocomp1.setText("Add");
        addTocomp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTocomp1ActionPerformed(evt);
            }
        });
        jPanel4.add(addTocomp1);
        addTocomp1.setBounds(540, 540, 144, 39);

        tab_comp.setBackground(new java.awt.Color(153, 153, 153));
        tab_comp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tab_comp.setShowHorizontalLines(true);
        tab_comp.setShowVerticalLines(true);
        tab_comp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_compMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_comp);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(470, 110, 930, 380);

        jLabel19.setIcon(new javax.swing.ImageIcon("D:\\صور\\shopping-cart-with-pill-foils-copy-space.jpg")); // NOI18N
        jPanel4.add(jLabel19);
        jLabel19.setBounds(0, 0, 1570, 1077);

        Tab.addTab("Companys", jPanel4);

        jPanel1.add(Tab);
        Tab.setBounds(0, 0, 1570, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1577, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void del_last1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_last1ActionPerformed
        // TODO add your handling code here:
        model2 = (DefaultTableModel) tab_Sales.getModel();
        int selectedRow = tab_Sales.getSelectedRow();
        model2.removeRow(selectedRow);
    }//GEN-LAST:event_del_last1ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        Search_for_a_category search = new Search_for_a_category();
        search.setVisible(true);
        search.pack();
        search.setLocationRelativeTo(null);
        search.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btn_searchActionPerformed

    private void date_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_fieldActionPerformed

    private void del_last5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_last5ActionPerformed
        try {
            model2 = (DefaultTableModel) tab_toDataBase.getModel();
            int selectedRow = tab_toDataBase.getSelectedRow();
            String id = ((tab_toDataBase.getValueAt(selectedRow,2)).toString());
            String Quary = "delete from dataOfDrugs where idOfDrugs=?";
            PreparedStatement stmt = con.prepareStatement(Quary);
            stmt.setString(1, id);
            stmt.executeUpdate();
            model2.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this,"Deleted success");
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,"Deleted Failed");
            
        }
    }//GEN-LAST:event_del_last5ActionPerformed
    public void showdata(){
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmcy","root", "eslam23467859");
            PreparedStatement stmt = con.prepareStatement(" select * from dataOfDrugs");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            //dm = (DefaultTableModel) tab_Sales.getModel();

            dm.addColumn("Name");
            dm.addColumn("Type");
            dm.addColumn("ID");
            dm.addColumn("Quantity");
            dm.addColumn("Selling Price ");
            dm.addColumn("Purchasing Price ");
            dm.addColumn("start Date ");
            dm.addColumn("Ended Date");
            dm.addColumn("Value of discount");
            while(set.next()){
                String r[] = { set.getString(1), set.getString(2) ,set.getString(3),set.getString(4),set.getString(5) ,set.getString(6),set.getString(7),set.getString(8),set.getString(9)};
                dm.addRow(r);
            }
            tab_toDataBase.setModel(dm);
        }
        catch(Exception ex)
        {
            System.out.println("Error ");
        }
    }
    private void btn_savetodatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_savetodatabaseActionPerformed

        try {PreparedStatement stmt  = con.prepareStatement("insert into dataOfDrugs (nameOfDrugs,typeOfDrugs,quantityOfDrugs,sellingOfDrugs ,perchasingOfDrugs ,startdate ,endeddate,discount)values(?,?,?,?,?,?,?,?)");
            stmt.setString(1,nameofdrugs.getText());
            stmt.setString(2, type_com.getSelectedItem().toString());
            stmt.setLong(3,Long.parseLong(quantityofDrugs.getText()));
            stmt.setDouble(4,Double.parseDouble(dateofcomp.getText()));
            stmt.setDouble(5,Double.parseDouble(perchasingofdrugs.getText()));
            stmt.setString(6, st_date.getText());
            stmt.setString(7,end_date.getText());
            stmt.setInt(8,Integer.parseInt(discountofdrugs.getText()));
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"Added successed");
        } catch (SQLException ex) {
            //Logger.getLogger(AddDrugs.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"connection Failed");
        }
    }//GEN-LAST:event_btn_savetodatabaseActionPerformed

    private void addToDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToDatabaseActionPerformed

        
        DefaultTableModel model = (DefaultTableModel) tab_toDataBase.getModel();
        model.insertRow(model.getRowCount(),new Object[]{nameofdrugs.getText(),type_com.getSelectedItem(),idofDrugs.getText(),quantityofDrugs.getText(),dateofcomp.getText(),perchasingofdrugs.getText(),st_date.getText(),end_date.getText(),discountofdrugs.getText()});
        tab_toDataBase.setModel(model);
    }//GEN-LAST:event_addToDatabaseActionPerformed
    
    public void showDataCompany(){
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmcy","root", "eslam23467859");
            PreparedStatement stmt = con.prepareStatement(" select * from pharmacy");
            ResultSet set = stmt.executeQuery();
            DefaultTableModel dm = new DefaultTableModel();
            //dm = (DefaultTableModel) tab_Sales.getModel();

            dm.addColumn("Name of company");
            dm.addColumn("ID");
            dm.addColumn("The Prodect");
            dm.addColumn("start Date ");
            dm.addColumn("Ended Date");
            dm.addColumn("Purchasing Price ");
            dm.addColumn("Selling Price ");
            while(set.next()){
                String r[] = { set.getString(1) , set.getString(2) ,set.getString(3),set.getString(4),set.getString(5) ,set.getString(6),set.getString(7)};
                dm.addRow(r);
            }
            tab_comp.setModel(dm);
        }
        catch(SQLException ex)
        {
            System.out.println("Error ");
        }
    }
    private void tab_toDataBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_toDataBaseMouseClicked
        // TODO add your handling code here:
        int row_num = tab_toDataBase.getSelectedRow();
        String name =tab_toDataBase.getValueAt(row_num, 0).toString();
        String id =tab_toDataBase.getValueAt(row_num, 2).toString();
        String quantity =tab_toDataBase.getValueAt(row_num, 3).toString();
        String sellingPrice =tab_toDataBase.getValueAt(row_num, 4).toString();
        String PurchasingPrice =tab_toDataBase.getValueAt(row_num, 5).toString();
        String start =tab_toDataBase.getValueAt(row_num, 6).toString();
        String end =tab_toDataBase.getValueAt(row_num, 7).toString();
        String discount =tab_toDataBase.getValueAt(row_num, 8).toString();
        //nameofdrugs.setText(number);
        nameofdrugs.setText(name);
        idofDrugs.setText(id);
        quantityofDrugs.setText(quantity);
        dateofcomp.setText(sellingPrice);
        perchasingofdrugs.setText(PurchasingPrice);
        discountofdrugs.setText(discount);
        st_date.setText(start);
        end_date.setText(end);
        //ExpirationTF.setText(ExpirationDate);
    }//GEN-LAST:event_tab_toDataBaseMouseClicked

    private void date_field2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date_field2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date_field2ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
       try {
            //Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy", "root", "root");
            PreparedStatement stat = con.prepareStatement("SELECT sum(perchasingOfDrugs) from pharmcy.dataOfDrugs;");
            ResultSet rs = stat.executeQuery(); 
            if(rs.next()){
            double r = Double.parseDouble(rs.getString(1))- Double.parseDouble(tab_Sales.getValueAt(tab_Sales.getSelectedRow(), 4).toString());
            
                text_total.setText(Double.toString(r));
            } 
            
        } catch (SQLException ex) {
            Logger.getLogger(NewJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_totalActionPerformed

    private void addTocompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTocompActionPerformed
        try {
            // TODO add your handling code here:
            //model1.insertRow(model1.getRowCount(),new Object[]{nameOfDrugs.getText(),idOfDrugs.getText(),quantityOfDrugs.getText(),sellingOfDrugs.getText(),perchasingOfDrugs.getText(),endeddate.getText()});
            PreparedStatement stmt  = con.prepareStatement("insert into pharmacy (PM_NameOfCompany,PH_Name ,PH_Date,PH_Expiriation ,PH_PurchasingPrice ,PH_SellingPrice)values(?,?,?,?,?,?)");
            stmt.setString(1,nameofcomp.getText());
            stmt.setString(2,prodectofcomp.getText());
            stmt.setString(3, stofcomp.getText());
            stmt.setString(4,expofcomp.getText());
            stmt.setDouble(5,Double.parseDouble(purchasingofcomp.getText()));
            stmt.setDouble(6,Double.parseDouble(sellingofcomp.getText()));
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"Added successed");
        } catch (SQLException ex) {
            //Logger.getLogger(AddDrugs.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Added Failed");
        }
        
    }//GEN-LAST:event_addTocompActionPerformed

    private void tab_compMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_compMouseClicked
        // TODO add your handling code here:
        int row_num = tab_comp.getSelectedRow();
        String name =tab_comp.getValueAt(row_num, 0).toString();
        String id =tab_comp.getValueAt(row_num, 1).toString();
        String prodect =tab_comp.getValueAt(row_num, 2).toString();
        String stdata =tab_comp.getValueAt(row_num, 3).toString();
        String expdata =tab_comp.getValueAt(row_num, 4).toString();
        String perchasing  =tab_comp.getValueAt(row_num, 5).toString();
        String selling =tab_comp.getValueAt(row_num, 6).toString();
        //nameofdrugs.setText(number);
        nameofcomp.setText(name);
        idofcomp.setText(id);
        prodectofcomp.setText(prodect);
        stofcomp.setText(stdata);
        expofcomp.setText(expdata);
        purchasingofcomp.setText(perchasing);
        sellingofcomp.setText(selling);
    }//GEN-LAST:event_tab_compMouseClicked

    private void updatecompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatecompActionPerformed
        // TODO add your handling code here:
        add.setVisible(true);
        try {
            // TODO add your handling code here:
            //model1.insertRow(model1.getRowCount(),new Object[]{nameOfDrugs.getText(),idOfDrugs.getText(),quantityOfDrugs.getText(),sellingOfDrugs.getText(),perchasingOfDrugs.getText(),endeddate.getText()});
            //int selectrow = tab_comp.getSelectedRow();
            int id=Integer.parseInt(tab_comp.getValueAt(tab_comp.getSelectedRow(),1).toString());
            PreparedStatement stmt  = con.prepareStatement("update pharmacy set PM_NameOfCompany=?,PH_Name=? ,PH_Date=?,PH_Expiriation=? ,PH_PurchasingPrice=? ,PH_SellingPrice=? where PH_Id="+id);
            stmt.setString(1,nameofcomp.getText());
            stmt.setString(2,prodectofcomp.getText());
            stmt.setString(3, stofcomp.getText());
            stmt.setString(4,expofcomp.getText());
            stmt.setDouble(5,Double.parseDouble(purchasingofcomp.getText()));
            stmt.setDouble(6,Double.parseDouble(sellingofcomp.getText()));
            //stmt.setInt(7,(.toString()));
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update successed");
        } catch (SQLException ex) {
            //Logger.getLogger(AddDrugs.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Failed To Update");
        }
    }//GEN-LAST:event_updatecompActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        nameofdrugs.setText("");
        idofDrugs.setText("");
        quantityofDrugs.setText("");
        dateofcomp.setText("");
        perchasingofdrugs.setText("");
        discountofdrugs.setText("");
        st_date.setText("");
        end_date.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void del_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_compActionPerformed
         try {
            model2 = (DefaultTableModel) tab_comp.getModel();
            int selectedRow = tab_comp.getSelectedRow();
            String id = ((tab_comp.getValueAt(selectedRow, 1)).toString());
            String Quary = "delete from pharmacy where PH_Id=?";
            PreparedStatement stmt = con.prepareStatement(Quary);
            stmt.setString(1, id);
            stmt.executeUpdate();
            model2.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this,"Deleted success");
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,"Deleted Failed");
            
        }
        
    }//GEN-LAST:event_del_compActionPerformed

    private void addTocomp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTocomp1ActionPerformed
        // TODO add your handling code here:
        add.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tab_comp.getModel();
        model.insertRow(model.getRowCount(),new Object[]{nameofcomp.getText(),idofcomp.getText(),prodectofcomp.getText(),stofcomp.getText(),expofcomp.getText(),purchasingofcomp.getText(),sellingofcomp.getText()});
        tab_comp.setModel(model);
        
    }//GEN-LAST:event_addTocomp1ActionPerformed

    private void Reset_compActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reset_compActionPerformed
        nameofcomp.setText("");
        idofcomp.setText("");
        prodectofcomp.setText("");
        stofcomp.setText("");
        expofcomp.setText("");
        purchasingofcomp.setText("");
        sellingofcomp.setText("");
    }//GEN-LAST:event_Reset_compActionPerformed

    private void update_perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_perActionPerformed
        add.setVisible(true);
        try {
            int id=Integer.parseInt(tab_toDataBase.getValueAt(tab_toDataBase.getSelectedRow(),2).toString());
            PreparedStatement stmt  = con.prepareStatement("update dataOfDrugs set nameOfDrugs=?,typeOfDrugs=?,quantityOfDrugs=?,sellingOfDrugs=? ,perchasingOfDrugs=? ,startdate=? ,endeddate=?,discount=? where idOfDrugs="+id);
            stmt.setString(1,nameofdrugs.getText());
            stmt.setString(2, type_com.getSelectedItem().toString());
            stmt.setLong(3,Long.parseLong(quantityofDrugs.getText()));
            stmt.setDouble(4,Double.parseDouble(dateofcomp.getText()));
            stmt.setDouble(5,Double.parseDouble(perchasingofdrugs.getText()));
            stmt.setString(6, st_date.getText());
            stmt.setString(7,end_date.getText());
            stmt.setInt(8,Integer.parseInt(discountofdrugs.getText()));
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(this,"Update successed");
        } catch (SQLException ex) {
            //Logger.getLogger(AddDrugs.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Failed To Update");
        }
    }//GEN-LAST:event_update_perActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        add_per.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton Reset_comp;
    private javax.swing.JPanel Selling;
    public javax.swing.JTabbedPane Tab;
    private javax.swing.JPanel add;
    private javax.swing.JButton addToDatabase;
    private javax.swing.JButton addTocomp;
    private javax.swing.JButton addTocomp1;
    private javax.swing.JPanel add_per;
    private javax.swing.JButton btn_savetodatabase;
    private javax.swing.JButton btn_search;
    public static javax.swing.JTextField date_field;
    public static javax.swing.JTextField date_field2;
    public static javax.swing.JTextField dateofcomp;
    private javax.swing.JButton del_comp;
    private javax.swing.JButton del_last1;
    private javax.swing.JButton del_last5;
    public static javax.swing.JTextField discountofdrugs;
    public static javax.swing.JTextField end_date;
    public static javax.swing.JTextField expofcomp;
    public static javax.swing.JTextField idofDrugs;
    public static javax.swing.JTextField idofcomp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTextField nameofcomp;
    public static javax.swing.JTextField nameofdrugs;
    private javax.swing.JPanel perchasing;
    public static javax.swing.JTextField perchasingofdrugs;
    public static javax.swing.JTextField prodectofcomp;
    public static javax.swing.JTextField purchasingofcomp;
    public static javax.swing.JTextField quantityofDrugs;
    public static javax.swing.JTextField sellingofcomp;
    public static javax.swing.JTextField st_date;
    public static javax.swing.JTextField stofcomp;
    public javax.swing.JTable tab_Sales;
    private javax.swing.JTable tab_comp;
    public static javax.swing.JTable tab_toDataBase;
    private javax.swing.JTextField text_total;
    private javax.swing.JButton total;
    private javax.swing.JComboBox<String> type_com;
    private javax.swing.JButton update_per;
    private javax.swing.JButton updatecomp;
    // End of variables declaration//GEN-END:variables
}
